export interface Book {
    $key?: string;
    coverimg?:string;
    issuedate?:string;
    month?:number;
    objective?:string;
    summary?:string;
    theme?:string;
    year?:string;
        chilevocab?:string,
        japanphrases?:string,
        notes?:string,
        pois?:string,
        proverbs?:string,
        articletypes?:string,
        flavorcolors?:string,
        kanjis?:string,
        quotes?:string,
        bcphotos?:string,
        ecpphotos?:string,
        fcphotos?:string,
        ofdphotos?:string,
        storya?:string,
        storyb?:string,
        storyc?:string,
        storybl?:string,
        storyli?:string,
        storyaf?:string
}